//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.28 at 09:00:22 AM CEST 
//


package com.example.soapexample.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.soapexample.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.soapexample.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateMovieResponse }
     * 
     */
    public UpdateMovieResponse createUpdateMovieResponse() {
        return new UpdateMovieResponse();
    }

    /**
     * Create an instance of {@link MovieSoap }
     * 
     */
    public MovieSoap createMovieSoap() {
        return new MovieSoap();
    }

    /**
     * Create an instance of {@link DeleteMovieRequest }
     * 
     */
    public DeleteMovieRequest createDeleteMovieRequest() {
        return new DeleteMovieRequest();
    }

    /**
     * Create an instance of {@link CreateUserResponse }
     * 
     */
    public CreateUserResponse createCreateUserResponse() {
        return new CreateUserResponse();
    }

    /**
     * Create an instance of {@link UserSoap }
     * 
     */
    public UserSoap createUserSoap() {
        return new UserSoap();
    }

    /**
     * Create an instance of {@link CreateReviewResponse }
     * 
     */
    public CreateReviewResponse createCreateReviewResponse() {
        return new CreateReviewResponse();
    }

    /**
     * Create an instance of {@link ReviewSoap }
     * 
     */
    public ReviewSoap createReviewSoap() {
        return new ReviewSoap();
    }

    /**
     * Create an instance of {@link UpdateMovieRequest }
     * 
     */
    public UpdateMovieRequest createUpdateMovieRequest() {
        return new UpdateMovieRequest();
    }

    /**
     * Create an instance of {@link DeleteReviewRequest }
     * 
     */
    public DeleteReviewRequest createDeleteReviewRequest() {
        return new DeleteReviewRequest();
    }

    /**
     * Create an instance of {@link DeleteRateRequest }
     * 
     */
    public DeleteRateRequest createDeleteRateRequest() {
        return new DeleteRateRequest();
    }

    /**
     * Create an instance of {@link CreateReviewRequest }
     * 
     */
    public CreateReviewRequest createCreateReviewRequest() {
        return new CreateReviewRequest();
    }

    /**
     * Create an instance of {@link UpdateReviewRequest }
     * 
     */
    public UpdateReviewRequest createUpdateReviewRequest() {
        return new UpdateReviewRequest();
    }

    /**
     * Create an instance of {@link CreateUserRequest }
     * 
     */
    public CreateUserRequest createCreateUserRequest() {
        return new CreateUserRequest();
    }

    /**
     * Create an instance of {@link CreateMovieRequest }
     * 
     */
    public CreateMovieRequest createCreateMovieRequest() {
        return new CreateMovieRequest();
    }

    /**
     * Create an instance of {@link UpdateReviewResponse }
     * 
     */
    public UpdateReviewResponse createUpdateReviewResponse() {
        return new UpdateReviewResponse();
    }

    /**
     * Create an instance of {@link CreateRateResponse }
     * 
     */
    public CreateRateResponse createCreateRateResponse() {
        return new CreateRateResponse();
    }

    /**
     * Create an instance of {@link RateSoap }
     * 
     */
    public RateSoap createRateSoap() {
        return new RateSoap();
    }

    /**
     * Create an instance of {@link CreateMovieResponse }
     * 
     */
    public CreateMovieResponse createCreateMovieResponse() {
        return new CreateMovieResponse();
    }

    /**
     * Create an instance of {@link DeleteMovieResponse }
     * 
     */
    public DeleteMovieResponse createDeleteMovieResponse() {
        return new DeleteMovieResponse();
    }

    /**
     * Create an instance of {@link DeleteUserRequest }
     * 
     */
    public DeleteUserRequest createDeleteUserRequest() {
        return new DeleteUserRequest();
    }

    /**
     * Create an instance of {@link DeleteReviewResponse }
     * 
     */
    public DeleteReviewResponse createDeleteReviewResponse() {
        return new DeleteReviewResponse();
    }

    /**
     * Create an instance of {@link CreateRateRequest }
     * 
     */
    public CreateRateRequest createCreateRateRequest() {
        return new CreateRateRequest();
    }

    /**
     * Create an instance of {@link UpdateRateResponse }
     * 
     */
    public UpdateRateResponse createUpdateRateResponse() {
        return new UpdateRateResponse();
    }

    /**
     * Create an instance of {@link UpdateUserRequest }
     * 
     */
    public UpdateUserRequest createUpdateUserRequest() {
        return new UpdateUserRequest();
    }

    /**
     * Create an instance of {@link UpdateRateRequest }
     * 
     */
    public UpdateRateRequest createUpdateRateRequest() {
        return new UpdateRateRequest();
    }

    /**
     * Create an instance of {@link UpdateUserResponse }
     * 
     */
    public UpdateUserResponse createUpdateUserResponse() {
        return new UpdateUserResponse();
    }

    /**
     * Create an instance of {@link DeleteUserResponse }
     * 
     */
    public DeleteUserResponse createDeleteUserResponse() {
        return new DeleteUserResponse();
    }

    /**
     * Create an instance of {@link DeleteRateResponse }
     * 
     */
    public DeleteRateResponse createDeleteRateResponse() {
        return new DeleteRateResponse();
    }

}
