//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.28 at 09:00:22 AM CEST 
//


package com.example.soapexample.soap;

import com.example.soapexample.mapper.Soap;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rateSoap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rateSoap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="rate" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="movie" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rateSoap", propOrder = {
    "id",
    "rate",
    "movie",
    "author"
})
public class RateSoap implements Soap {

    protected long id;
    @XmlElement(required = true)
    protected BigInteger rate;
    protected long movie;
    protected long author;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRate() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRate(BigInteger value) {
        this.rate = value;
    }

    /**
     * Gets the value of the movie property.
     * 
     */
    public long getMovie() {
        return movie;
    }

    /**
     * Sets the value of the movie property.
     * 
     */
    public void setMovie(long value) {
        this.movie = value;
    }

    /**
     * Gets the value of the author property.
     * 
     */
    public long getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     */
    public void setAuthor(long value) {
        this.author = value;
    }

}
